name: First Workflow 

on:
  push:
    branches:
      - main

jobs:
  first_job:
    name: This is the first job
    runs-on: ubuntu-latest
    steps:
      - name: check_out
        id: check_out
        uses: actions/checkout@v3
        
      - name: cat_content
        run: |
          echo $(cat hello-world.txt)
