name: First Workflow 

on:
  push:
    branches:
      - main

jobs:
  first_job:
    name: This is the first job
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        id: first_step
        run: echo Hello World!    
